GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJJcnN5YWQiLCJlbWFpbCI6Imlyc3lhZGFpcjExQGdtYWlsLmNvbSIsImlhdCI6MTY0ODEyOTc1OSwiZXhwIjoxNjQ4MTI5Nzc0fQ.8kkyoDYmeads5fU8kplw8AUD9sK637fBKrCq03eYq2A

###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name": "Irsyad2",
    "email": "irsyadair12@gmail.com",
    "password": "1234567",
    "confPassword" : "1234567"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "irsyadair11@gmail.com",
    "password": "123456"
}

###
GET   http://localhost:5000/token

###
DELETE    http://localhost:5000/logout